### ISSUE TITLE
Feature Request: Clean with random characters

### ISSUE THREAD

**Issue by CookedApps** [3chospirits/badwords-filter#1]
### Idea:
When providing an array of characters for `cleanWith`, unclean words will be replaced with a random string consisting of these characters.

#### Example:
```javascript
const config = {
    cleanWith: ["#", "!", "?", "*"],
};
const filter = new Filter(config);

const cleaned = filter.clean("badword");
// results in "#?*!?#"
```

Feel free to leave feedback. I can try to implement it if you don't have time.
Thank you for making this neat library!

**Comment by CookedApps** [comment]
I opened a PR #2

**Comment by 3chospirits** [comment]
Seems like a nice feature to have! Thanks for the PR. Have merged with the main branch :)
